data:
  raw_path: "data/dataset_v1.csv"
  target: "MedHouseVal"
  test_size: 0.2
  random_state: 42

models:
  linear_regression:
    type: "linear_regression"

  random_forest:
    type: "random_forest"
    n_estimators: 150
    max_depth: 8
    random_state: 42

  gradient_boosting:
    type: "gradient_boosting"
    n_estimators: 200
    learning_rate: 0.1
    max_depth: 3
    random_state: 42
